# Generated by Django 2.1.7 on 2019-05-05 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_department', models.CharField(max_length=8)),
                ('course_id', models.PositiveSmallIntegerField(default=0)),
                ('course_dept_id', models.CharField(max_length=9)),
                ('num_lectures', models.PositiveSmallIntegerField(default=0)),
                ('num_labs', models.PositiveSmallIntegerField(default=0)),
                ('current_num_TA', models.PositiveSmallIntegerField(default=0)),
                ('current_num_lectures', models.PositiveSmallIntegerField(default=0)),
                ('current_num_labs', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.CharField(default='no TA', max_length=50)),
                ('lab_section', models.CharField(max_length=3)),
                ('lab_location', models.CharField(default='NOT SET', max_length=50)),
                ('lab_time', models.TimeField(default=datetime.time(16, 0))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(default='no instructor', max_length=50)),
                ('TA', models.CharField(default='no TA', max_length=50)),
                ('lecture_section', models.CharField(max_length=3)),
                ('lecture_location', models.CharField(default='NOT SET', max_length=50)),
                ('lecture_time', models.TimeField(default=datetime.time(16, 0))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TACourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(default='000.000.0000', max_length=12)),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('type', models.CharField(default='person', max_length=20)),
                ('isLoggedOn', models.BooleanField(default=False)),
                ('address', models.CharField(default='not set', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tacourse',
            name='TA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.User'),
        ),
        migrations.AddField(
            model_name='tacourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.Course'),
        ),
        migrations.AddField(
            model_name='instructorcourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.User'),
        ),
    ]
