# Generated by Django 2.2 on 2019-05-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_section',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_section',
            field=models.CharField(max_length=3),
        ),
    ]
