# Generated by Django 2.1.7 on 2019-05-07 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
