# Generated by Django 2.1.7 on 2019-05-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='TA',
            field=models.CharField(default='no TA', max_length=50),
        ),
    ]
