# Generated by Django 2.1.7 on 2019-05-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0002_auto_20190502_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='not set', max_length=50),
        ),
    ]
