# Generated by Django 2.1.7 on 2019-05-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='not set', max_length=100),
        ),
    ]
